FROM mcr.microsoft.com/dotnet/sdk:10.0

ARG FOLDER=/app

COPY --chown=1000:1000 . /app

WORKDIR $FOLDER

USER  1000:1000

RUN dotnet tool restore \
    && dotnet tool run libman restore

EXPOSE 5054

ENV ASPNETCORE_URLS=http://+:5054

ENV ASPNETCORE_ENVIRONMENT=Development

ENV ASPNETCORE_HTTPS_PORT=""

CMD [ "dotnet", "watch", "--no-launch-profile"]
